### ISSUE TITLE
Test Issue Creation

### ISSUE THREAD

**Issue by comographer** [nomadcoders/git-practice#130]
# This is a test issue

- I am currently taking Git & Github for Everyone course
- Wanted to try creating issue

## A small suggestion

- as for your youtube channel, really enjoying it ❤
- one of the biggest takeaways from your courses like Kokoa Clone, or Vanilla JS is that begginers get to learn the best practices.
  _ex) BEM for HTML/CSS, adding init() for Vanilla JS, etc._
- I was wondering if you have video plan for below topic
- **Best way to find common/best practices when coding**
- This would really help out a lot of beginners 😊

**Comment by itdorok** [comment]
erqerqerqer

**Comment by serranoarevalo** [comment]
Love the idea!
